//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Clubs = new HashSet<Club>();
            this.Delegates = new HashSet<Delegate>();
            this.Halls = new HashSet<Hall>();
            this.Referees = new HashSet<Referee>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public int PostalCode { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Delegate> Delegates { get; set; }
        public virtual ICollection<Hall> Halls { get; set; }
        public virtual ICollection<Referee> Referees { get; set; }
    }
}
