//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.ClubOfficials = new HashSet<ClubOfficial>();
            this.GuestTeams = new HashSet<GuestTeam>();
            this.HomeTeams = new HashSet<HomeTeam>();
            this.Players = new HashSet<Player>();
        }
    
        public int ClubId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string JerseyColorHome { get; set; }
        public string JerseyColorGuest { get; set; }
        public int CityId { get; set; }
    
        public virtual City Cities { get; set; }
        public virtual ICollection<ClubOfficial> ClubOfficials { get; set; }
        public virtual ICollection<GuestTeam> GuestTeams { get; set; }
        public virtual ICollection<HomeTeam> HomeTeams { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
