//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegate
    {
        public Delegate()
        {
            this.Match = new HashSet<Match>();
        }
    
        public int DelegateId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CityId { get; set; }
    
        public virtual ICollection<Match> Match { get; set; }
        public virtual City City { get; set; }
    }
}
