//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        public int ClubOfficialId { get; set; }
        public int MatchId { get; set; }
        public Nullable<int> Warning { get; set; }
        public Nullable<int> Suspension { get; set; }
        public Nullable<int> Disqualification { get; set; }
        public Nullable<int> DisqualificationAndReport { get; set; }
    
        public virtual ClubOfficial ClubOfficial { get; set; }
        public virtual Match Match { get; set; }
    }
}
