//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatchReporterEntities : DbContext
    {
        public MatchReporterEntities()
            : base("name=MatchReporterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<ClubOfficial> ClubOfficial { get; set; }
        public virtual DbSet<Delegate> Delegate { get; set; }
        public virtual DbSet<GuestTeam> GuestTeam { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<League> League { get; set; }
        public virtual DbSet<Manage> Manage { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Play> Play { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Referee> Referee { get; set; }
        public virtual DbSet<RefereePair> RefereePair { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
