//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.GuestTeams = new HashSet<GuestTeam>();
            this.HomeTeams = new HashSet<HomeTeam>();
            this.Manages = new HashSet<Manage>();
            this.Plays = new HashSet<Play>();
        }
    
        public int MatchId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Round { get; set; }
        public int Spectators { get; set; }
        public int RefereePairId { get; set; }
        public int LeagueId { get; set; }
        public int DelegateId { get; set; }
        public int HallId { get; set; }
    
        public virtual Delegate Delegates { get; set; }
        public virtual ICollection<GuestTeam> GuestTeams { get; set; }
        public virtual Hall Halls { get; set; }
        public virtual ICollection<HomeTeam> HomeTeams { get; set; }
        public virtual League Leagues { get; set; }
        public virtual ICollection<Manage> Manages { get; set; }
        public virtual ICollection<Play> Plays { get; set; }
        public virtual RefereePair RefereePairs { get; set; }
    }
}
