//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public int PlayerId { get; set; }
        public int MatchId { get; set; }
        public int Goals { get; set; }
        public int Goals7m { get; set; }
        public Nullable<int> Warning { get; set; }
        public Nullable<int> SuspensionFirst { get; set; }
        public Nullable<int> SuspensionSecond { get; set; }
        public Nullable<int> SuspensionThird { get; set; }
        public Nullable<int> Disqualification { get; set; }
        public Nullable<int> DisqualificationAdnReport { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
