//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referee
    {
        public Referee()
        {
            this.RefereePair = new HashSet<RefereePair>();
            this.RefereePair1 = new HashSet<RefereePair>();
        }
    
        public int RefereeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CityId { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<RefereePair> RefereePair { get; set; }
        public virtual ICollection<RefereePair> RefereePair1 { get; set; }
    }
}
